# Generated by Django 3.2.21 on 2023-12-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainTableInput', '0002_alter_victim_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
